variables:
  USER_PROJECT: "onlineshop"
  PATH_PROJECT: "/home/${USER_PROJECT}/${CI_PROJECT_NAME}"
  ZIP_VERSION: $CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA-$CI_COMMIT_TAG.zip
  # online-shop-frontend-aabbccdd-pipeline-be-1.zip

stages:
  - build
  - push
  - deploy

build:
  stage: build
  variables:
    GIT_STRATEGY: clone
  script:
    # - npm install --force
    - zip -r $ZIP_VERSION .
  tags: 
    - online-shop-runner-build-shell
  only:
    - tags

push:
  stage: push
  variables: 
    GIT_STRATEGY: none
  script: 
    - curl -X PUT -u $ARTIFACT_USER:$ARTIFACT_PASS -T $ZIP_VERSION "$ARTIFACT_URL/$ZIP_VERSION"
  tags: 
    - online-shop-runner-build-shell
    
deploy:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  script:
    - sudo su ${USER_PROJECT} -c "cd ${PATH_PROJECT};rm -rf *;curl -u $ARTIFACT_USER:$ARTIFACT_PASS -O ${ARTIFACT_URL}/${ZIP_VERSION}; unzip -o ${ZIP_VERSION}"
    - sudo chown -R ${USER_PROJECT}:${USER_PROJECT} ${PATH_PROJECT}
    - sudo su ${USER_PROJECT} -c "cd ${PATH_PROJECT}; pm2 delete ${CI_PROJECT_NAME}; npm i --force; pm2 start npm --name '${CI_PROJECT_NAME}' -- run 'start'"
  tags:
    - online-shop-runner-dev-shell
  only:
    - tags

