variables:
  USER_PROJECT: "onlineshop"
  PATH_PROJECT: "/home/${USER_PROJECT}/${CI_PROJECT_NAME}"
  ZIP_VERSION: $CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA-$CI_COMMIT_TAG.zip
  # online-shop-backend-aabbccdd-pipeline-be-1.zip

stages:
  - build
  - push
  - deploy

build:
  stage: build
  variables:
    GIT_STRATEGY: clone
  script:
    - dotnet restore
    - zip -r $ZIP_VERSION .
  tags: 
    - online-shop-runner-build-shell
  only:
    - tags

push:
  stage: push
  variables: 
    GIT_STRATEGY: none
  script: 
    - curl -X PUT -u $ARTIFACT_USER:$ARTIFACT_PASS -T $ZIP_VERSION "$ARTIFACT_URL/$ZIP_VERSION"
  tags: 
    - online-shop-runner-build-shell
    
deploy:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  script:
    - sudo su ${USER_PROJECT} -c "cd ${PATH_PROJECT};rm -rf *;curl -u $ARTIFACT_USER:$ARTIFACT_PASS -O ${ARTIFACT_URL}/${ZIP_VERSION}; unzip -o ${ZIP_VERSION}"
    - sudo chown -R ${USER_PROJECT}:${USER_PROJECT} ${PATH_PROJECT}
    - |
      pid=$(sudo netstat -plunt | grep :5214 | awk '{print $7}' | cut -d'/' -f1) || true
      if [ -n "$pid" ]; then
        sudo kill -9 ${pid}
      fi
    - sudo su ${USER_PROJECT} -c "cd ${PATH_PROJECT}; nohup dotnet run > output.txt 2>&1 &"
  tags:
    - online-shop-runner-dev-shell
  only:
    - tags

